script:
- "./gradlew build"
language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
deploy:
  provider: bintray
  file: ".travis_descriptor.json"
  user: sladomic
  key:
    secure: iSCFSmxmR4rhUx24tQ3AlKOVNOCdrZpdMaqpXPl31QqIRvryHvyBFg3Zb8OEu1hkPgzMf3ue0edpdn222YegABzKdDxoGPJbzU2rW0xDkgbEzuZRBnvodg5yY7rGt43UtBZ4TDYbN4Ho81ST7QsKD4ux8XpDD+x7SXGY3wcJE2MXe1RSFU1gcpJ45M8HbBoKuuJ8wksVscKfnWsbyqRtAuu2CkcLHKJgFs2/zZ5z/QiBwO0u//qhZ+rO/KTZdYsHIPyLFcR/vHmdcydlZM4qtYbqrS8Ra/HVbvxWfLjFp/dQQXvL4OOWq5Bqq3JL251R/mP2yYMg63vWrkikOw4wTOFy8TIytfbCvanFqpo5NGo6yB3ORx2e3jf3sZtJtGPBZWwmAFB0OuQFwx9ugK4UvzWpsPKmvhwedIH8mw8Ya/0wmryAR0x12cdcN3TOTFfSiNM6T/37PdKIhWIbf7kmFfDUD8nWzqPwkZPPPgXlh9WY6LxFnyZcDv8/3UZbysZNG0GKZ0f1Mm3V83Dmk4QGljjRPBTbN84uRa0ZAuyeQpssSNFxsM+VPs3yX98cBNSUuDz22j0ZYsM4p3cOmPK+If+/n2fwU/g4mMb9gm/plUY9AXexvMUE7Jhm1uyOV1qiGtUwAU1gvbgEi9hf54ChGbT7OOdW6cA91CXvSwk4B5I=
